# Site settings
title: Zzivi
header-img: img/home-bg.jpg
icon-img: img/icons/amazon.png
email: support@zzivi.com
description: "Passionate about technology!"
url: "http://zzivi.com"
twitter_username:
github_username:  zzivi
facebook_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Plugins
whitelist: []
gems:      [jekyll-paginate]

# Members information. Shown on About page.
members:
  - name: Romina Liuzzi
    position: Android Developer
    text:
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:romina.liuzzi@zzivi.com
      - title: github
        url: http://github.com/rliuzzi
      - title: linkedin
        url: http://es.linkedin.com/in/rliuzzi        
  - name: Daniel Viorreta
    position: DevOps
    text:
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:daniel.viorreta@zzivi.com
      - title: github
        url: http://github.com/danielviorreta
      - title: linkedin
        url: http://es.linkedin.com/in/danielviorreta