# Site settings
title: Zzivi
email: support@zzivi.com
description: > # this means to ignore newlines until "baseurl:"
  Nos gusta la tecnología.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zzivi.com" # the base hostname & protocol for your site
twitter_username:
github_username: 

# Build settings
markdown: kramdown
