# Site settings
title: Zzivi
header-img: img/home-bg.jpg
email: support@zzivi.com
description: "Frikis de la tecnología!"
url: "http://zzivi.com"
twitter_username:
github_username:  zzivi
facebook_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
